package org.huber.keytool.ui.wizard.storepasswd;

import javax.swing.JPanel;
import org.huber.keytool.settings.KeytoolSettings;
import org.huber.keytool.ui.wizard.ChangeObserverOfWizardPanel;
import org.huber.keytool.ui.wizard.ObserverablePanel;
import org.openide.util.NbBundle;

public final class StorePasswordVisualPanel2 extends JPanel implements ObserverablePanel {
    
    /** Creates new form StorePasswordVisualPanel2 */
    public StorePasswordVisualPanel2() {
        initComponents();
    }
    
    public String getName() {
        return NbBundle.getMessage( StorePasswordVisualPanel2.class, "NAME_StorePasswordVisualPanel2" );
    }
    
    public void bind(ChangeObserverOfWizardPanel changeObserver) {
        changeObserver.bindDocumentListener( this.keyStorePasswordField.getDocument() );
        changeObserver.bindDocumentListener( this.keyStorePasswordRetypedField.getDocument() );
    }
    
    public ValidUserEntryResult isValidUserEntry() {
        boolean isValid = true;
        final ObserverablePanel.ValidUserEntryResult vuer = new ObserverablePanel.ValidUserEntryResult();
        
        KeytoolSettings keytoolSettings = KeytoolSettings.getDefault();
        final int MIN_LENGTH = keytoolSettings.getMinPasswordLength();
        
        isValid = isValid && checkPasswordLength(MIN_LENGTH);
        if (!isValid) {
            final String msg = NbBundle.getMessage( StorePasswordVisualPanel2.class, "ERR_INVALID_STORE_PASSWORD_LENGTH", Integer.valueOf(MIN_LENGTH) );
            vuer.setInvalidMessage( msg );
            return vuer;
        }
        isValid = isValid && checkPasswordFields();
        if (!isValid) {
            final String msg = NbBundle.getMessage( StorePasswordVisualPanel2.class, "ERR_MISMATHC_STORE_PASSWORD" );
            vuer.setInvalidMessage( msg );
            return vuer;
        }
        return vuer;
    }
    
    private boolean checkPasswordLength(int minLength) {
        boolean isValid = true;
        
        isValid = isValid && (this.keyStorePasswordField.getPassword().length == 0 || this.keyStorePasswordField.getPassword().length >= minLength);
        isValid = isValid && (this.keyStorePasswordRetypedField.getPassword().length == 0 || this.keyStorePasswordRetypedField.getPassword().length >= minLength);
        return isValid;
    }
    
    private boolean checkPasswordFields() {
        final char[] pw1 = this.keyStorePasswordField.getPassword();
        final char[] pw2 = this.keyStorePasswordRetypedField.getPassword();
        
        boolean checkPasswordFields = true;
        
        checkPasswordFields = checkPasswordFields && pw1 != null;
        checkPasswordFields = checkPasswordFields && pw2 != null;
        checkPasswordFields = checkPasswordFields && pw1.length == pw2.length;
        for (int i = 0; checkPasswordFields && i < pw1.length; i++ ) {
            checkPasswordFields = checkPasswordFields && pw1[i] == pw2[i];
        }
        
        return checkPasswordFields;
    }
    private final static String EMPTY_STRING = "";
    
    public void reset() {
        this.storeFileNameTextField.setText( EMPTY_STRING );
        this.keyStorePasswordField.setText( EMPTY_STRING );
        this.keyStorePasswordRetypedField.setText( EMPTY_STRING );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel3 = new javax.swing.JLabel();
        keyStorePasswordField = new javax.swing.JPasswordField();
        keyStorePasswordRetypedField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        storeFileNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, "New Store Password");

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, "New Store Password (confirmed)");

        storeFileNameTextField.setEditable(false);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, "Store File Name");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel3)
                    .add(jLabel1)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(storeFileNameTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(keyStorePasswordField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .add(keyStorePasswordRetypedField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(storeFileNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(keyStorePasswordField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(keyStorePasswordRetypedField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField keyStorePasswordField;
    private javax.swing.JPasswordField keyStorePasswordRetypedField;
    private javax.swing.JTextField storeFileNameTextField;
    // End of variables declaration//GEN-END:variables
    
    public char[] getKeyStorePassword() {
        return this.keyStorePasswordField.getPassword();
    }
    
    void setSelectedKeyStoreFile(String selectedKeyStoreFile) {
        this.storeFileNameTextField.setText( selectedKeyStoreFile );
    }
    
}

