package org.huber.keytool.ui.wizard.certreq;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import org.huber.keytool.ui.filefilter.CertificateRequestFileFilterFactory;
import org.huber.keytool.ui.wizard.ChangeObserverOfWizardPanel;
import org.huber.keytool.ui.wizard.ObserverablePanel;
import org.openide.util.NbBundle;

public final class SelectCertReqFilePanel extends JPanel implements ObserverablePanel {
    //private FileFilter keyStoreFileFilter;
    
    /** Creates new form LoadKeyStoreVisualPanel1 */
    public SelectCertReqFilePanel() {
        initComponents();
        
        //this.keyStoreFileFilter = new KeyStoreFilter();
        
        this.certReqFileButton.addActionListener( new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                handleCertReqFileAction(e);
            }
        });
    }
    
    private void handleCertReqFileAction(ActionEvent e) {
        final JFileChooser jfc = new JFileChooser();
        jfc.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        CertificateRequestFileFilterFactory.addChoosableFileFilter( jfc );
        jfc.setCurrentDirectory( this.currentDirectory );
        int rc = jfc.showSaveDialog( this );
        if (rc == JFileChooser.APPROVE_OPTION) {
            final File selectedFile = jfc.getSelectedFile();
            this.certReqFileTextField.setText( selectedFile.toString() );
        }
    }
    
    public String getName() {
        return org.openide.util.NbBundle.getMessage(ChooseCertReqOptionsPanel.class, "NAME_SelectCertRequestFilePanel");
    }
    
    public void bind(ChangeObserverOfWizardPanel changeObserver) {
//        final String[] propertyNames = new String[] {
//            JFileChooser.SELECTED_FILES_CHANGED_PROPERTY,
//            JFileChooser.SELECTED_FILE_CHANGED_PROPERTY
//        };
        
        changeObserver.bindDocumentListener( this.certReqFileTextField.getDocument() );
    }
    
    public ObserverablePanel.ValidUserEntryResult isValidUserEntry() {
        ObserverablePanel.ValidUserEntryResult vuer = new ObserverablePanel.ValidUserEntryResult();
        
        boolean isValid = true;
        final String selectedFileAsString = this.certReqFileTextField.getText();
        isValid = isValid && selectedFileAsString != null;
        isValid = isValid && selectedFileAsString.length() > 0;
        if (!isValid) {
            final String msg = NbBundle.getMessage( SelectCertReqFilePanel.class, "ERR_SELECT_CERTREQ_FILE" );
            vuer.setInvalidMessage( msg );
            return vuer;
        }
        
        final File selectedFile = new File(selectedFileAsString);
        isValid = isValid && selectedFile != null;
        if (!isValid) {
            final String msg = NbBundle.getMessage( SelectCertReqFilePanel.class, "ERR_SELECT_CERTREQ_FILE" );
            vuer.setInvalidMessage( msg );
            return vuer;
        }
        isValid = isValid && !selectedFile.exists();
        if (!isValid) {
            final String msg = NbBundle.getMessage( SelectCertReqFilePanel.class, "ERR_SELECT_CERTREQ_FILE_EXISTS" );
            vuer.setInvalidMessage( msg );
            return vuer;
        }
        return vuer;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        certReqFileLabel = new javax.swing.JLabel();
        certReqFileTextField = new javax.swing.JTextField();
        certReqFileButton = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(certReqFileLabel, org.openide.util.NbBundle.getMessage(SelectCertReqFilePanel.class, "LBL_CertReqFile")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(certReqFileButton, org.openide.util.NbBundle.getMessage(SelectCertReqFilePanel.class, "LBL_SelectCertificateRequestFile")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(certReqFileLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(certReqFileTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(certReqFileButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(certReqFileLabel)
                    .add(certReqFileTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(certReqFileButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton certReqFileButton;
    private javax.swing.JLabel certReqFileLabel;
    private javax.swing.JTextField certReqFileTextField;
    // End of variables declaration//GEN-END:variables
    
    public void reset() {
    }
        
    File getSelectedFile() {
        File selectedFile = new File(this.certReqFileTextField.getText());
        return selectedFile;
    }
    private File currentDirectory = null;
    
    void setCurrentDirectoryOrFilecurrentDirectoryOrFile(String currentDirectoryOrFilecurrentDirectoryOrFile) {
        if (currentDirectoryOrFilecurrentDirectoryOrFile != null) {
            //this.keyStoreFileChooser.setCurrentDirectory( new File( currentDirectoryOrFilecurrentDirectoryOrFile ) );
            this.currentDirectory = new File( currentDirectoryOrFilecurrentDirectoryOrFile );
        }
    }

    
}

