/*
 * MainPanel.java
 *
 * Created on 20. September 2006, 22:47
 */

package org.huberb.httppost.ui;

import org.huberb.httppost.model.HttpPostForm;

/**
 *
 * @author  HuberB1
 */
public class MainPanel extends javax.swing.JPanel {
    private HttpPostForm httpPostForm;
    
    /** Creates new form MainPanel */
    public MainPanel() {
        initComponents();        
        httpPostForm = new HttpPostForm();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        requestPanel = new org.huberb.httppost.ui.RequestPanel();
        requestHeaderPanel = new org.huberb.httppost.ui.RequestHeaderPanel();
        responsePanel = new org.huberb.httppost.ui.ResponsePanel();

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(requestPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(responsePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addContainerGap())
            .add(requestHeaderPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(requestPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(requestHeaderPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(responsePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.huberb.httppost.ui.RequestHeaderPanel requestHeaderPanel;
    private org.huberb.httppost.ui.RequestPanel requestPanel;
    private org.huberb.httppost.ui.ResponsePanel responsePanel;
    // End of variables declaration//GEN-END:variables

    //---
    public HttpPostForm getHttpPostForm() {
        this.requestPanel.getHttpPostForm( this.httpPostForm );
        this.requestHeaderPanel.getHttpPostForm( this.httpPostForm );
        return httpPostForm;
    }
    public void updateHttpPostFormResponseOnly(HttpPostForm httpPostForm ) {
        this.responsePanel.updateHttpPostForm( httpPostForm );
    }
    public void updateHttpPostForm(HttpPostForm httpPostForm ) {
        this.requestPanel.updateHttpPostForm( httpPostForm );
        this.requestHeaderPanel.updateHttpPostForm( httpPostForm );
        this.responsePanel.updateHttpPostForm( httpPostForm );
    }
    
    public void xxx() {
        // get the state
    }
    
}
