package org.huberb.regexpnb;

import java.io.Serializable;
import org.huberb.regexpnb.ui.RegexpPanel;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
final class RegexpTopComponent extends TopComponent {

    private static final long serialVersionUID = 1L;

    private static RegexpTopComponent instance;
    
    private RegexpPanel regexpPanel;

    private RegexpTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(RegexpTopComponent.class, "CTL_RegexpTopComponent"));
        setToolTipText(NbBundle.getMessage(RegexpTopComponent.class, "HINT_RegexpTopComponent"));
//        setIcon(ImageUtilities.loadImage("SET/PATH/TO/ICON/HERE", true));
        
        this.regexpPanel = new RegexpPanel();
        this.add( this.regexpPanel );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());

    }
    // </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * Gets default instance. Don't use directly, it reserved for '.settings' file only,
     * i.e. deserialization routines, otherwise you can get non-deserialized instance.
     */
    public static synchronized RegexpTopComponent getDefault() {
        if (instance == null) {
            instance = new RegexpTopComponent();
        }
        return instance;
    }

    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    public void componentOpened() {
        // TODO add custom code on component opening
    }

    public void componentClosed() {
        // TODO add custom code on component closing
    }

    /** replaces this in object stream */
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    protected String preferredID() {
        return "RegexpTopComponent";
    }

    final static class ResolvableHelper implements Serializable {
        private static final long serialVersionUID = 1L;
        public Object readResolve() {
            return RegexpTopComponent.getDefault();
        }
    }

}
