package org.huber.keytool.ui.wizard.genkey;

import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;

import org.huber.keytool.ui.wizard.ChangeObserverOfWizardPanel;
import org.huber.keytool.ui.wizard.ObserverablePanel;
import org.openide.util.NbBundle;

public final class GenKeySummaryPanel extends JPanel implements ObserverablePanel {
    
    /** Creates new form GenKeyVisualPanel3 */
    public GenKeySummaryPanel() {
        initComponents();
    }
    
    public String getName() {
        return NbBundle.getMessage( GenKeySummaryPanel.class, "NAME_GenKeySummaryPanel" );
    }
    
    public void bind(ChangeObserverOfWizardPanel changeObserver) {
        changeObserver.bindChangeListener( this.keyDataIsOkayCheckBox );
    }
    
    public ObserverablePanel.ValidUserEntryResult isValidUserEntry() {
        ObserverablePanel.ValidUserEntryResult  vuer = new ObserverablePanel.ValidUserEntryResult();
        boolean isValid = true; 
        
        isValid = isValid && this.keyDataIsOkayCheckBox.isSelected();
        if (!isValid) {
            final String msg = NbBundle.getMessage( GenKeySummaryPanel.class, "ERR_SELECT_KEY_DATA_IS_OK");
            vuer.setInvalidMessage( msg );
        }
        return vuer;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        keyDataTextPane = new javax.swing.JTextPane();
        keyDataIsOkayCheckBox = new javax.swing.JCheckBox();

        keyDataTextPane.setEditable(false);
        jScrollPane1.setViewportView(keyDataTextPane);

        keyDataIsOkayCheckBox.setMnemonic(Integer.parseInt(org.openide.util.NbBundle.getMessage(GenKeySummaryPanel.class, "IDX_KeyDataIsOkay")));
        keyDataIsOkayCheckBox.setText(org.openide.util.NbBundle.getMessage(GenKeySummaryPanel.class, "LBL_KeyDataIsOkay"));
        keyDataIsOkayCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        keyDataIsOkayCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .add(keyDataIsOkayCheckBox))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(keyDataIsOkayCheckBox)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JScrollPane jScrollPane1;
    private JCheckBox keyDataIsOkayCheckBox;
    private JTextPane keyDataTextPane;
    // End of variables declaration//GEN-END:variables
    
    public void reset() {
        final String EMPTY_STRING = "";
        this.keyDataIsOkayCheckBox.setSelected(false);
        this.keyDataTextPane.setText(EMPTY_STRING);
    }
    
    public void setText( String text ) {
        this.keyDataIsOkayCheckBox.setSelected(false);
        this.keyDataTextPane.setText( text );
    }
    
    
}

